spring:
  profiles:
    active: dev

server:
  compression:
    enabled: true
    mime-types: text/html, text/html; charset=UTF-8,\
      text/xml, text/xml; charset=UTF-8,\
      text/plain, text/plain; charset=UTF-8,\
      text/css, text/css; charset=UTF-8,\
      text/javascript, text/javascript; charset=UTF-8,\
      application/javascript, application/javascript; charset=UTF-8,\
      application/json, application/json; charset=UTF-8,\
      application/xml, application/xml; charset=UTF-8,\
      font/woff, font/woff; charset=UTF-8